source 'https://github.com/CocoaPods/Specs.git'

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})', __dir__]).strip

def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve('#{script}', {paths: [process.argv[1]]})", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, '15.1'
prepare_react_native_project!
use_modular_headers!

setup_permissions(['Microphone'])

linkage = ENV['USE_FRAMEWORKS']
use_frameworks! :linkage => linkage.to_sym if linkage

target 'muzic' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  $FirebaseVersion = '11.12.0'

  # Firebase
  pod 'Firebase/CoreOnly', $FirebaseVersion
  pod 'Firebase/Analytics', $FirebaseVersion
  pod 'FirebaseInstallations', $FirebaseVersion

  # Facebook SDKs
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  # Problematic pods with modular header fixes
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo', :modular_headers => true
  pod 'react-native-branch', :path => '../node_modules/react-native-branch', :modular_headers => true

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath])

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FB_SONARKIT_ENABLED=1'

        # Default to modular imports
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'

        # Apply non-modular include allowance selectively
        if ['react-native-netinfo', 'react-native-branch', 'react-native-webrtc', 'RNFBApp', 'RNPermissions', 'RNSound'].include?(target.name)
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
          config.build_settings['DEFINES_MODULE'] = 'YES'
        end
      end

      # WebRTC specific hack
      if target.name == 'react-native-webrtc'
        target.build_configurations.each do |config|
          config.build_settings['MODULEMAP_FILE'] = '$(PODS_TARGET_SRCROOT)/ios/RCTWebRTC/module.modulemap'
        end
      end
    end
  end
end
